### ISSUE TITLE
Broken Link Minion: allow HEAD / GET request timeout value to be configured per domain

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2179]
### Problem description

It may take over 60 seconds (one test took over 90 seconds) for some providers to serve an HTTP `HEAD` request to test a download link of a large file.

Our current default timeout time is 20 seconds. 

The short timeout will make the HEAD request fail and broken link minion will issue another GET request which is not ideal (as it will process all downloaded data and took much longer time)

Although, you can configure it via parameter:
```
.option("requestOpts", {
            describe:
                "The default options to use for the JS request library when making HTTP HEAD/GET requests",
            type: "string",
            coerce: coerceJson("requestOpts"),
            default:
                process.env.REQUEST_OPTS || JSON.stringify({ timeout: 20000 })
        })
```
We should allow this settings to be configured per domain (as long timeout may not be desired for most domains ). e.g.:

```yaml
headRequestTimeOutConfig:
    data.csiro.au: 120
    data.gov.au: 30
    data.act.gov.au: 30
getRequestTimeOutConfig:
    data.csiro.au: 120
    data.gov.au: 30
    data.act.gov.au: 30
```
