### ISSUE TITLE
Incompatible colors in CSS

### ISSUE THREAD

**Issue by sajidanower23** [magda-io/magda#2680]
**Describe the bug**
CSS overrides with incompatible colors.
In the file `magda-web-client/src/index.scss`:
```scss
    button.au-btn,
    a.au-btn {
        background: $AU-colordark-background;
        color: $AU-colordark-foreground-text;
    }

    .au-btn.au-btn--primary,
    a.au-btn.au-btn--primary {
        background: $AU-colordark-background;
        color: $AU-colordark-foreground-text;
        border-color: $AU-color-foreground-action;
    }

    .au-btn.au-btn--tertiary,
    a.au-btn.au-btn--tertiary {
        color: $AU-colordark-foreground-focus;
        background: transparent;
        border-color: transparent;
    }

    .au-btn.au-btn--secondary,
    a.au-btn.au-btn--secondary {
        background: transparent;
        color: $AU-color-foreground-action;
    }

```

Some of the classes have (potentially) white color on transparent background, which makes it effectively invisible.
