### ISSUE TITLE
Solution of adding Authentication Plugin to Gateway without rebuild it

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2774]
### Summary

Follow-up ticket for https://github.com/TerriaJS/nsw-digital-twin/issues/332.

But may also need for other Magda clients who want to implement their own Single Sign-On Solution.

This ticket will help to keep them on our mainstream Magda without forking it.

### Possible Solution:
- Package authentication plugin as independent microservice (HTTP)
  - Expect authentication requests/redirects to be proxied to the microservice via current gateway Auth Router
- gateway Auth Router Should proxy any requests to the path `/auth/login/remote-authenticator/[this-remote-authenticator-name]/*`
  - Here [this-remote-authenticator-name] is the name remote authenticator service
- Gateway can be configured in this way (via helm):
```yaml
externalAuthenticators:
  - name: remote-authenticator-a
     route: http://remote-authenticator-a/
```
