### ISSUE TITLE
Update magda-config repo with instructions & example of `chart-based` more generic deployment config

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2827]
## Description

> This PR: https://github.com/magda-io/magda-config/pull/10 should be merged before this ticket or its content should be used when working on this ticket. 

### Background

Currently, the `magda` chart includes many connector source related contents which is useful for our own deployment. 

Some examples are:
- In chart.yaml (of Magda chart), we have the followings:
```yaml
- name: magda-ckan-connector
    version: 0.0.57-0
    alias: connector-dga
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-dga
``` 
- In values.yaml (of Magda chart), we have the followings:
```
connector-dga:
  config:
    id: dga
    name: "data.gov.au"
    sourceUrl: "https://data.gov.au/data/"
    pageSize: 1000
    ignoreHarvestSources: ["*"]
```

Those examples above are source-related (i.e. DGA ckan source related) and is included by our `magda` chart. 

At this moment, our generic [magda-config](https://github.com/magda-io/magda-config) repo still use the single values-file ([config.yaml](https://github.com/magda-io/magda-config/blob/dc5fd9caa72377a5b1d7b11455675f95b80816dd/config.yaml)) deployment approach which requires referencing the `magda` chart.

We probably can update the [magda-config](https://github.com/magda-io/magda-config) repo with the `chart-based` deployment config, which allows:
- reference more generic `magda-core` as the dependency
- the user only include the specific connector config that he needs in his deployment config chart

### Solution

Replace the [config.yaml](https://github.com/magda-io/magda-config/blob/dc5fd9caa72377a5b1d7b11455675f95b80816dd/config.yaml) in [magda-config](https://github.com/magda-io/magda-config) with a config helm chart named `magda-config`. This helm chart should come with the following two files:
- `Chart.yaml`: sample chart definition file which defines the magda modules required. 
Here is an example:
```yaml
apiVersion: v2
name: "magda-config"
version: "0.0.57-0"
dependencies:
  - name: magda-core
    version: 0.0.57-0
    repository: https://charts.magda.io

# Add more required connector like:
  - name: magda-ckan-connector
    version: 0.0.57-0
    alias: ckan-connector-1
    repository: https://charts.magda.io
```
- `values.yaml`: the chart value file. We should reuse most content of [config.yaml](https://github.com/magda-io/magda-config/blob/dc5fd9caa72377a5b1d7b11455675f95b80816dd/config.yaml) without appropriate adjustment.

When deploy, we should use the following command instead:
```bash
helm upgrade --install --timeout 9999s --wait magda ./magda-config
```  
here, `./magda-config` is the path to your local config chart folder. You don't need to specify a values file as the chart values file includes all config.

### Acceptance Criteria
- Replace the [config.yaml](https://github.com/magda-io/magda-config/blob/dc5fd9caa72377a5b1d7b11455675f95b80816dd/config.yaml) in [magda-config](https://github.com/magda-io/magda-config) with a config helm chart named `magda-config`:
  - Use `magda-core` as dependency
  - Includes comments & examples that can achieve the similar functionality of the current [config.yaml](https://github.com/magda-io/magda-config/blob/dc5fd9caa72377a5b1d7b11455675f95b80816dd/config.yaml) config file.
- Update the document with:
  - How to deploy with the `magda-config` chart
  - how to extend it with more connectors or minions
- Update the terraform module to make it use `magda-config` chart for deployment. (should merge or look at [this PR](https://github.com/magda-io/magda-config/pull/10) first)
