### ISSUE TITLE
Solution of auto secrets replicator for ease of deployment

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2918]
## Description

We now deploy OpenFaaS serverless functions to separate namespace (e.g. `magda-openfaas-fn`).

For more complicated functionality, the function might need to access the secrets/config map created in main namespace.

e.g. this function: https://github.com/magda-io/magda-function-history-report

We can ask users to manually copy the required secrets and/or configMap to openFaaS namespace. 

But it might be good to introduce an automated solution based on:

https://github.com/mittwald/kubernetes-replicator

What we need is:
- Ask the user to install kubernetes-replicator (once only per cluster)
- Modify the create secrets tool to make sure the secrets is created with the following annotations (assume openfaas function namespace is `magda-openfaas-fn`):
```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "magda-openfaas-fn"
data:
  key1: <value>
```
- Add the following `empty` secret definition (for copying secret `auth-secrets`) in Magda chart (assume main namespace is `magda`):
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-replica
  annotations:
    replicator.v1.mittwald.de/replicate-from: magda/auth-secrets
data: {}
```

We can add more `empty` secret (or configMap) definitions to `Magda` chart (not `magda-core`) when built-in function requires more along the line.
