### ISSUE TITLE
Add Helm Automatically Roll Deployments Support (Auto Restart Pods based on secret / configMap Dependencies)

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2925]
**Is your feature request related to a problem? Please describe.**

Add Helm Automatically Roll Deployments Support (Auto Restart Pods based on secret / configMap Dependencies)

Helm 3 added support of `Automatically Roll Deployments`

https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

We probably should adopt it for 2 use cases:
- Auto-restart pods based on its configMap / secrets dependencies changes.
  - i.e. suppose pod A requires configMap B & Secrets C to work, the pod will restart if any of B or C's content changes even deployment/pod A's parameter remains the same.
This can be done via the following annotation:
```yaml
annotations:
  checksum/config-b: {{ include (print $.Template.BasePath "/path-to-configmap/configmap.yaml") . | sha256sum }}
  checksum/secret-c: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
```
It might not be convenient (or secure) to generate a hash from a `secret.yaml` file. 
We probably should update our `create-secrets` tool to generate the hash as part of the secret generation process.
And add an optional parameter `secret-hash` to all charts' deployment.

- A better alternative to our `--recreate-pods` usage
  - We currently use `--recreate-pods` in test `dev` CI script to force re-start all pods. However, this switch is deprecated. We should use `Roll Deployments` to achieve the same. 
  - e.g.: Add a `forceRestart` value to all chart's value files. If its value == `true`, we will add the following annotation to the deployment: 
```yaml
annotations:
  rollme: {{ randAlphaNum 5 | quote }}
```
