### ISSUE TITLE
Allow `createGenericProxy` proxy all method 

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2928]
**Is your feature request related to a problem? Please describe.**

https://github.com/magda-io/magda/blob/3de6aa17e37e222693cc7a6d98229cbc01503ff6/magda-gateway/src/createGenericProxy.ts#L12

Here we only allow proxy GET method. Some web modules used by terria requires other methods as well.

We should simply change `get` to `all` here.

### Updates on 21th Aug 2020:

Eventually address it in a more generic way:

- generalise the function of createApiRouter and rename it as createGenericProxyRouter
- Allow configuring webRoutes in a way of similar to routes (i.e. specify methods, auth etc)
    - Accept simple string value as target as well (which assume route GET method, no auth)
- Make preview-map route to be added via webRoutes

So now, you can either configure a route like:
```yaml
webRoutes:
  preview-map: http://preview-map:6110
```
in which case assume it's a GET only route that has no auth.

Or specify more details:
```yaml
webRoutes:
  preview-map: 
    to: http://preview-map:6110
    auth: false
    method:
      - get  # `all` means all methods
```
