### ISSUE TITLE
Gateway should proxy all GET requests to registry-read-only pods

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3024]
### Gateway should proxy all GET requests to registry-read-only pods
We have registry-read-only pods/services to serve read-only registry requests.
They are designed to reduce the workload from the `registry-full` service that allows writes (we only can have one `registry-full` pod ).
However, `registry-full` service is still the default access endpoint behinds `/api/v0/registry`.
Therefore, unless you send requests to `/api/v0/registry-read-only`, `registry-full` is still serving most of "read" requests (People who crawl registry API is likely to use this default endpoint ).
To solve this, we should make gateway proxy all GET requests that sent to `/api/v0/registry` to registry-read-only pods.

~[http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) probably can help this.~

Update: we made gateway support new (optional) syntax for method (current config is still supported and not affected):
```
registry:
    to: http://registry-api/v0
    methods:
    - method: get
      target: http://registry-api-read-only/v0
    - method: head
      target: http://registry-api-read-only/v0
    - method: options
      target: http://registry-api-read-only/v0
    - method: post
      target: http://registry-api/v0
    - method: put
      target: http://registry-api/v0
    - method: patch
      target: http://registry-api/v0
    - method: delete
      target: http://registry-api/v0
    auth: true
```
- The main idea is to proxy incoming gateway request by HTTP method. 
  - All GET requests will be forwarded to read-only registry nodes
- However, Hooks API GET endpoints are only available from main registry node (Some webhook info is from registry event processing actor. Thus, can only be retrieved from the main node). We will:  
  - Proxy `/registry/hooks` at the gateway to the main registry API hooks endpoint.
    - However, expressjs order router routes by the sequence of registering routes with expressjs, rather than longer path got higher priority.  Therefore, route `/registry/hooks` might still be overwritten by route `/registry`. We will re-order all routes configuration (by length of seqment) before set-up proxy to avoid this issue.
