### ISSUE TITLE
Ability to supply external react component to replace built-in UI components of magda-web-client

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3099]
### Motivation

One use case is supply a customised header & footer components that can connect to external API without forking magda-web-client.

### Technical Challenges
How to customise existing webpack config to:
- Share the same version React 
- External component should bundled as UMD lib that expecting React libs as externals
- Control the bundling process so that selected libs (e.g. React) will be exported as UMD pack and export as seperate file
- Main bundle expects excluded libs as global exports

**Comment by t83714** [comment]
An example repo has been created for demostrating how to create external react component plugins:

https://github.com/magda-io/magda-plugin-ui-component-examples

To config Magda to load the plugin UI components, we can configure via web-server (See PR https://github.com/magda-io/magda/pull/3102):

You can instruct Magda to load your Plugin UI components via `magad-web-server` module Helm Config. e.g.:

```yaml
web-server:
  externalUIComponents:
    - "https://exmaple.com/assets/libs/MagdaPluginComponentHeader.js"
    - "https://exmaple.com/assets/libs/MagdaPluginComponentFooter.js"
```

We also need to configure Magda Gateway module `CSP` config accordingly to make sure scripts from `exmaple.com` are allowed. e.g.:

```yaml
gateway:
  csp:
    browserSniff: false
    directives:
      scriptSrc:
      - "'self'"
      - "'unsafe-inline'"
      - exmaple.com
      - exmaple.com
      - "blob:"
      objectSrc:
      - "'none'"
      workerSrc:
      - "'self'"
      - "blob:"
```
