### ISSUE TITLE
Add AWS RDS support to Helm Chart

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3124]
### Add AWS RDS support to Helm Chart

Assume user use the following AWS RDS config:
- RDS lives in VPC1
- Magda / EKS lives in VPC2
- A peer connection is created between VPC1 & VPC2 (DNS resolution from VPC to private IP is turn on)
- Assume RDS access endpoint is: xxxx.rds.amazonaws.com

### Solutions:

Magda will access RDS via `ExternalName` type service. e.g.:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: auth-db
spec:
  type: ExternalName
  externalName: xxxx.rds.amazonaws.com
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
```

### Acceptance Criteria
- Allow to turn off:
  - in cluster DB option: `useCombinedDb`
  - And `useCloudSql` option
  - turn on `useAwsRdsDb` option
- Transparent: No impact to existing code / config
- DB pass will still read from "cloudsql-db-credentials" secrets (for backward compatibility ) & `password` field
- allow to change master DB username (currently hardcoded to "postgres")
