### ISSUE TITLE
Configuration of the minio PVC size from the global values.yaml

### ISSUE THREAD

**Issue by bouleq** [magda-io/magda#3206]
Hi everyone, I am using Magda as a data catalog, and I encountered this issue:

I am storing my data directly in Magda (not in an external storage), but the minio's PVC size is only 10Go by default. 
I thought I could configure it from the global values.yaml but it doesn't seem to be possible, so I had to change the value in the packaged chart in magda/charts/magda-core/charts/storage-api/values.yaml.

I think it could be nice to add the possibility to configure this parameter directly in the global values.yaml

**Comment by t83714** [comment]
@bouleq 
Helm allows you to pass down the values to sub chart (and sub chart's subchart) with 
Therefore, you don't have to modify the storage API default value file --- `storage-api/values.yaml` file to overwrite the minio config (the document is here: https://github.com/magda-io/magda/blob/master/deploy/helm/internal-charts/storage-api/README.md).

Instead, you can (depends on your chart hierarchy):
- if you deploy [`magda` chart](https://github.com/magda-io/magda/blob/master/deploy/helm/magda/README.md) directly, you can put the following in the values file that you supply via `helm upgrade / install` `-f` switch:
```yaml
magda-core:
  storage-api:
    minio:
      persistence:
        size: 123G
```
- if you use a deployment wrapper chart and declare [`magda` chart](https://github.com/magda-io/magda/blob/master/deploy/helm/magda/README.md) as one of the dependencies, you can put the following in the values file that you supply via `helm upgrade / install` `-f` switch:
```yaml
magda:
  magda-core:
    storage-api:
      minio:
        persistence:
          size: 123G
```
- if you use a deployment wrapper chart and declare [`magda-core` chart](https://github.com/magda-io/magda/blob/master/deploy/helm/magda-core/README.md) as one of the dependencies, you can put the following in the values file that you supply via `helm upgrade / install` `-f` switch:
```yaml
magda-core:
  storage-api:
    minio:
      persistence:
        size: 123G
```

If you have troubles of making values flowing through, you can use `--debug` to print out helm runtime computation values for debug:

```
helm upgrade --debug --dry-run --install --timeout 9999s -f [my config value files] [deployment name] [chart name]
```

More details can be found from here:

https://helm.sh/docs/helm/helm_upgrade/
