### ISSUE TITLE
Auto-create db password secrets with backwards compatibility

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3207]
# Auto-create db password secrets with backwards compatibility

There are two types of postgreSQL accounts get involved in Magda:
- `Superuser` account
  - We use default account `postgres` at this moment
  - The account is only used by DB migrator that 
    - Initialises the DB schema
    - Create `client` accounts (with less permissions) that are used by all services to access DB
- `Client` account
  - Auto created by migrator with `Superuser` account
  - used by all services to access DB

At this moment, the password for those accounts are stored in various secrets. e.g.:
- `Superuser` account password can be stored in 
  - no password if it's for local development only
  - part of `db-passwords` secrets
  - part of `cloudsql-db-credentials` secrets
- `Client` account password can be stored in 
  -  no password if it's for local development only
  - part of `db-passwords` secrets

When the user deploy magda, he needs to either manually create those secrets or use [create-secrets](https://www.npmjs.com/package/@magda/create-secrets) tool to create one.

To make it easier for users to deploy, we should:
- auto create the secrets during helm deployment so there is no extra steps before helm deployment
- store `Superuser` password (key: `postgresql-password`) & username (key: `username`) in secret `db-main-account-secret` 
  - key: `postgresql-password` is for meeting the requirements of [bitnami postgreSQL chart](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
- store `Client` accounts passwords in secrets with naming pattern `[db-name]-secret`
  -  password (key: `password`) & username (key: `username`)
- backwards compatibility. Existing deployment will still work and existing secrets will be auto copied to new secrets

### Solution

Use helm3's [new lookup API](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function). e.g. the secret can be:

```yaml
{{ if $secret -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "db-main-account-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: db-main-account-secret
type: Opaque
# 2. If the secret exists, write it back out (it'll be Base64 encoded so used the "data" key)
data:
{{- if $secret }}
  postgresql-password: {{ $secret.data.postgresql-password }}
# 3. If it doesn't exist ... create it 
{{- else }}
  postgresql-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
```
