### ISSUE TITLE
Gateway Chart should support an extra "additionalRoutes" field 

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3438]
### Gateway Chart should support an extra "additionalRoutes" field 
At this moment, users can config gateway API routes via the `routes` field.
However, once the user set the `routes` fields, he will have to list all API routes including system API routes.
Although this allow users to disable system routes, we should also provide a shortcut to users so he don't have to list all system API routes.
The "additionalRoutes" field is proposed for this propose.

Without `additionalRoutes` field, the user will have to config his own API by:
```yaml
routes:
  my-own-api:
    to: http://my-service/
  search:
        to: http://search-api/v0
        auth: true
  ...
  ... all other system API routes
```

With `additionalRoutes` field, the user can simply config his own API by:
```yaml
additionalRoutes:
  my-own-api:
    to: http://my-service/
```
