### ISSUE TITLE
When supply custom opa policy files via Helm chart config, we should allow path prefix to be removed

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3587]
### When supply custom opa policy files via Helm chart config, we should allow path prefix to be removed

When we have put all custom policy files in `policies` folder of the config helm chart and set helm chart config via `authorization-api.opa.customPolicyConfigMaps`, we often use [magda.filesToJson](https://github.com/magda-io/magda/blob/main/deploy/helm/magda-common/templates/_helpers.tpl#L35) named template as a helper to create configMap:

e.g.:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "test-opa-policies"
data:
  my_custom_policy_files.json: {{ include "magda.filesToJson" (dict "root" . "filePattern" "policies/**/*" "removePrefix" "policies/" ) }} 
```

This ticket is about introducing a `removePrefix` parameter. Therefore, when use `magda.filesToJson`, we can specify the path prefix `policies/` to be removed from supplied policy files. Otherwise, we will end up having a `policies` folder in the opa container policy directory.
